# Description:
#   Provides ApiDef access and ApiDef validation for TensorFlow python.

load("//machina:machina.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

filegroup(
    name = "python_api_def",
    srcs = glob(["*"]),
    visibility = ["//machina:internal"],
)
