# python/lib package
load("//machina:strict.default.bzl", "py_strict_library")

visibility = [
    "//machina:__subpackages__",
]

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    default_visibility = visibility,
    licenses = ["notice"],
)

py_strict_library(
    name = "__init__",
    srcs = ["__init__.py"],
    visibility = ["//machina:__subpackages__"],
    deps = [],
)
