load("@rules_shell//shell:sh_library.bzl", "sh_library")

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

sh_library(
    name = "ctpu",
    srcs = ["ctpu.sh"],
    deps = [],
)
