integration_tests_seanet_conv_GENERATOR_INPUTS := \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv0.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv1.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv2.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv3.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv4.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv5.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv6.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv7.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv8.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv9.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv10.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv11.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv12.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv13.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv14.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv15.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv16.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv17.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv18.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv19.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv20.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv21.tflite \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv0_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv0_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv1_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv1_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv2_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv2_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv3_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv3_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv4_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv4_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv5_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv5_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv6_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv6_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv7_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv7_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv8_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv8_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv9_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv9_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv10_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv10_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv11_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv11_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv12_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv12_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv13_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv13_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv14_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv14_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv15_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv15_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv16_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv16_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv17_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv17_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv18_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv18_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv19_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv19_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv20_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv20_golden_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv21_input0_int16.csv \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/conv21_golden_int16.csv \

integration_tests_seanet_conv_SRCS := \
$(MACHINA_ROOT)machina/lite/micro/integration_tests/seanet/conv/integration_tests.cc  \
$(MACHINA_ROOT)python/tflite_micro/python_ops_resolver.cc \


integration_tests_seanet_conv_HDR := \
$(MACHINA_ROOT)python/tflite_micro/python_ops_resolver.h \


$(eval $(call microlite_test,integration_tests_seanet_conv_test,\
$(integration_tests_seanet_conv_SRCS),$(integration_tests_seanet_conv_HDR),$(integration_tests_seanet_conv_GENERATOR_INPUTS)))