# Description:
# spectrogram test data packages.
load("//machina:machina.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

filegroup(
    name = "spectrogram_test_data",
    srcs = [
        "short_test_segment.wav",
        "short_test_segment_spectrogram.csv.bin",
        "short_test_segment_spectrogram_400_200.csv.bin",
    ],
    visibility = ["//visibility:public"],
)
