package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    default_visibility = ["//machina:internal"],
    licenses = ["notice"],
)

exports_files(glob(["*.html"]) + glob(["*.pb"]) + glob(["*.dot"]))
