path: "machina.AttrValue.ListValue"
tf_proto {
  descriptor {
    name: "ListValue"
    field {
      name: "s"
      number: 2
      label: LABEL_REPEATED
      type: TYPE_BYTES
    }
    field {
      name: "i"
      number: 3
      label: LABEL_REPEATED
      type: TYPE_INT64
      options {
        packed: true
      }
    }
    field {
      name: "f"
      number: 4
      label: LABEL_REPEATED
      type: TYPE_FLOAT
      options {
        packed: true
      }
    }
    field {
      name: "b"
      number: 5
      label: LABEL_REPEATED
      type: TYPE_BOOL
      options {
        packed: true
      }
    }
    field {
      name: "type"
      number: 6
      label: LABEL_REPEATED
      type: TYPE_ENUM
      type_name: ".machina.DataType"
      options {
        packed: true
      }
    }
    field {
      name: "shape"
      number: 7
      label: LABEL_REPEATED
      type: TYPE_MESSAGE
      type_name: ".machina.TensorShapeProto"
    }
    field {
      name: "tensor"
      number: 8
      label: LABEL_REPEATED
      type: TYPE_MESSAGE
      type_name: ".machina.TensorProto"
    }
    field {
      name: "func"
      number: 9
      label: LABEL_REPEATED
      type: TYPE_MESSAGE
      type_name: ".machina.NameAttrList"
    }
  }
}
