package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    default_visibility = [
        "//machina/core/tfrt/ifrt:__subpackages__",
        "//machina/core/tfrt/kernels:__subpackages__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "testdata",
    srcs = glob(
        ["*"],
    ),
)
