# Description:
# Old string tensors data package alias.

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

alias(
    name = "old_string_tensors",
    actual = "//machina/core/util/tensor_bundle/testdata/old_string_tensors:old_string_tensors_testdata",
    visibility = ["//visibility:public"],
)
