# Description:
# Graph properties test data.

load("//machina:machina.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

filegroup(
    name = "graph_properties_testdata",
    srcs = glob([
        "*.pbtxt",
        "*.pbtxt.html",
    ]),
    visibility = ["//visibility:public"],
)
