# Description:
# bmp test data package alias.

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

alias(
    name = "bmp_testdata",
    actual = "//machina/core/lib/bmp/testdata:bmp_testdata",
    visibility = ["//visibility:public"],
)
