path: "machina.saved_model.Asset"
tf_class {
  is_instance: "<class \'machina.python.trackable.asset.Asset\'>"
  is_instance: "<class \'machina.python.trackable.base.Trackable\'>"
  is_instance: "<type \'object\'>"
  member {
    name: "asset_path"
    mtype: "<type \'property\'>"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'path\'], varargs=None, keywords=None, defaults=None"
  }
}
