# Description:
# grappler testdata packages.

load("//machina:machina.default.bzl", "filegroup")

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    licenses = ["notice"],
)

filegroup(
    name = "test_file",
    srcs = [
        "test_file.txt",
    ],
    visibility = ["//machina/core/grappler/inputs:__pkg__"],
)
