# copybara:uncomment package(default_applicable_licenses = ["//machina:LICENSE"])

licenses(["notice"])

filegroup(
    name = "hexagon_delegate",
    srcs = ["HexagonDelegate.java"],
    visibility = ["//visibility:public"],
)
