# Example parser test data.

package(
    # copybara:uncomment default_applicable_licenses = ["//machina:license"],
    default_visibility = [
        "//machina/core/example:__pkg__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "example_parser_configuration_testdata",
    srcs = [
        "parse_example_graph_def.pbtxt",
    ],
)
